### ISSUE TITLE
gnet needs a way to update the node's address

### ISSUE THREAD

**Issue by b00f** [gallactic/Nova#23]
Currently gent is connecting to the localhost. In case we need to connect it a different address we need to manually edit the config file. 
However when the use install gnet globally it is not easy to find the config file. I think we need a way to update the node address for publishing txs. 
One suggestion is having new command for updating config file like: `gnet node <address>`

**Comment by ayinot** [comment]
Yeah agreed ! Or can we have the config file in root folder along with the accounts.json file. So that it is easy to edit.
